name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-custom'
      - '[0-9]+.[0-9]+.[0-9]+-custom-r[0-9]+'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set RUST_TARGET
      run: echo 'RUST_TARGET=${{ matrix.rust-target }}' >> $GITHUB_ENV

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        default: true
        profile: minimal

    - name: Build
      run: make

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/plugin.wasm
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
