name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-custom"
      - "[0-9]+.[0-9]+.[0-9]+-custom-r[0-9]+"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      - name: Build
        run: make

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/plugin.wasm
